### PR TITLE
Added tripcode support and for the client to set username and trip from the command line

### PR DESCRIPTION
**Pull request by Honeybunch**
This requires installation of the tripcode module with `npm install tripcode` but it allows the user to set a tripcode and username from the client's command line. Also migrated some code into the "join" function which means that a client has to request a join to the server. If no username is provided then one will be generated. Same with the color.

---
This change is [Reviewable](https://reviewable.io/reviews/yordok/palaverchatserver/1)

### CODE REVIEW

**Comment by yordok** [comment]
@Honeybunch, did you test this with the server, I see that you changed the `client.js` file to connect to `localhost` instead of the heroku server.

**Comment by Honeybunch** [comment]
I made changes to the server as well so this will need to be pushed up to heroku to be tested there. For now you can pull from my fork and test the changes locally as I have.

**Comment by Honeybunch** [comment]
I made the client.js client actually work as you would expect for a chat client. It chats.

**Comment by Honeybunch** [comment]
Also fixed an issue with room broadcasting.

**Pull request closed without merging**
